= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:
//:source-highlighter: highlightjs
:source-highlighter: prettify

Travis CI status:
image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]

== Introduction

include::../README.adoc[tags=content]

== Implementation

=== basic example

.prepare project
[source,bash]
----
mkdir -p basic

echo "node_modules" >> basic/.gitignore
echo "dist" >> basic/.gitignore
echo ".cache" >> basic/.gitignore
echo '{"scripts":{"start":"parcel src/","build":"parcel build src/index.html"}}' > basic/package.json

cd basic/
npm init -y
npm i -D parcel-bundler
----

.prepare project files
[source,bash]
----
mkdir -p src
touch src/index.html
touch src/styles.css
touch src/main.tsx
----

.main.tsx
[source,javascript]
----
include::../basic/src/main.js[]
----

.styles.css
[source,javascript]
----
include::../basic/src/styles.css[]
----

.index.html
[source,html]
----
include::../basic/src/index.html[]
----

.start development
[source,bash]
----
npm start
----

open http://localhost:1234/

.build bundle
[source,bash]
----
npm run build
----

.verify result
[source,bash]
----
npm i -g serve
serve dist/
----

open http://localhost:5000/

=== babel stage-0

parcel needed only .babelrc file and installed required presets

.add `.babelrc` file, install and configure presets: `env` and `stage-0`
[source,bash]
----
cp -Rf basic babel-stage-0
cd babel-stage-0/
echo '{"presets":["env","stage-0"]}' > .babelrc
npm i -D babel-preset-env babel-preset-stage-0
----

.now you can use some cool JS features:
[source,javascript]
----
include::../babel-stage-0/src/main.js[tags=content]
----

done.

=== react

.for React you need even less: just install react library and parcel will recognize everything for you!
[source,bash]
----
cp -Rf babel-stage-0 react
cd react/
npm i -S react react-dom
npm i -D babel-preset-react
echo '{"presets":["env","react"]}' > .babelrc
----

.add react component:
[source,javascript]
----
include::../react/src/components/echo-ehlo.js[]
----

.and update code in `src/main.tsx` file:
[source,javascript]
----
include::../react/src/main.js[tags=content]
----

build, run, verify...

done.

=== preact

.do necessary updates from react example:
[source,bash]
----
cp -Rf react preact
cd preact/

npm rm react react-dom babel-preset-react

npm i -S preact preact-compat
npm i -D babel-preset-preact babel-plugin-transform-class-properties

echo '{"presets":["env","preact"],"plugins":["transform-class-properties"]}' > .babelrc
----

.implement preact component:
[source,javascript]
----
include::../preact/src/components/echo-ehlo.js[]
----

.update entry point:
[source,javascript]
----
include::../preact/src/main.js[tags=content]
----

done.

=== vue

.to be able build vue apps, in addition to babel example you only need install vue and two dev packages:
[source,bash]
----
cp -Rf babel-stage-0 vue
cd vue/
npm i -S vue
npm i -D babel-preset-vue @vue/component-compiler-utils vue-template-compiler
echo '{"presets":["env","vue"]}' > .babelrc
----

.add vue component file: `AppUseState.vue`
[source,html]
----
include::../vue/src/components/App.vue[]
----

.main.tsx
[source,javascript]
----
include::../vue/src/main.js[tags=content]
----

=== yaml

.to be able to parse YAML we need js-yaml package:
[source,bash]
----
cp -Rf basic yaml
cd yaml/
npm i -ES js-yaml
----

.add YAML file:
[source,yaml]
----
include::../yaml/src/app.yaml[]
----

.main.tsx
[source,javascript]
----
include::../yaml/src/main.js[tags=content]
----

=== markdown

.to be able to parse YAML we need parcel-plugin-markdown package:
[source,bash]
----
cp -Rf basic markdown
cd markdown/
npm i -ED parcel-plugin-markdown
----

.add `app.md` file:
[source,markdown]
----
include::../markdown/src/app.md[]
----

.main.tsx
[source,javascript]
----
include::../markdown/src/main.js[tags=content]
----

NOTE: See also `markdowns` and `markdowns2` projects for non single md-file parsing use case...

=== markdowns (2)

example how we can handle lazy loading with parcel for markdown files lazy processing on runtime

.add `./src/posts` folder with some posts in markdown format:
[source,bash]
----
tree markdowns2/src/posts/
markdowns2/src/posts/
└── 2018
    └── 06
        ├── 29
        │   ├── 01-ololo.md
        │   └── 02-trololo.md
        └── 30
            ├── 01-javascript.md
            └── 02-bash.md
----

.`main.tsx` implementation:
[source,javascript]
----
include::../markdowns2/src/main.js[tags=content]
----

=== angularjs

with no comments - I tired....

.`./src/index.html`
[source,html]
----
include::../angularjs/src/index.html[]
----

.Main application bootstrap entrypoint: `./src/main.tsx`
[source,js]
----
include::../angularjs/src/main.js[tags=content]
----

.Application module config: `./src/app/index.js`
[source,js]
----
include::../angularjs/src/app/index.js[]
----

.Components module config: `./src/app/components/index.js`
[source,js]
----
include::../angularjs/src/app/components/index.js[]
----

.AppUseState module config: `./src/app/components/app/index.js`
[source,js]
----
include::../angularjs/src/app/components/app/index.js[]
----

.AppUseState component config: `./src/app/components/app/config.js`
[source,js]
----
include::../angularjs/src/app/components/app/config.js[]
----

.AppUseState component: `./src/app/components/app/component.js`
[source,js]
----
include::../angularjs/src/app/components/app/component.js[]
----

.AppUseState component controller: `./src/app/components/app/controller.js`
[source,js]
----
include::../angularjs/src/app/components/app/controller.js[]
----

=== react + bootstrap (4)

.prepare
[source,bash]
----
cp -Rf react react-bootstrap
cd react-bootstrap/
npm i -S bootstrap
npm i -ED babel-preset-env babel-preset-react babel-preset-stage-0
----

.file `.babelrc`
[source,json]
----
include::../react-bootstrap/.babelrc[]
----

.add bootstrap import and add some bootstrap class for styling:
[source,javascript]
----
include::../react-bootstrap/src/components/echo-ehlo.js[]
----

done.

=== typescript

.you don't needed anything special. parcel compiling typescript working out of the box
[source,ts]
----
include::../ts/src/main.ts[]
----

done.

=== rx.js + typescript

[source,bash]
----
cp -Rf ts rxts
cd rxts/
npm i -E rxjs
----

.file `main.tsx`:
[source, typescript]
----
include::../rxts/src/main.ts[]
----

done.

=== bootstrap.scss

[source,bash]
----
cp -Rf react-bootstrap sass-bootstrap
cd sass-bootstrap/
npm i
echo '$primary: #c63 !default;' > src/_variables.scss
mv src/styles.css src/styles.scss
# similary fix index.html: styles.css -> styles.scss
----

.remove import from file `src/components/echo-ehlo.js`:
[source, javascript]
----
// import 'bootstrap/dist/css/bootstrap.css';
----

.update file `styles.scss`:
[source, scss]
----
include::../sass-bootstrap/src/styles.scss[tags=bootstrap]
----

done.

=== react-hooks

.edit file `main.tsx`:
[source, js]
----
include::../react-hooks/src/app.js[]
----

done.

=== preact-hooks

.edit file `app.js`:
[source, js]
----
include::../preact-hooks/src/app.js[]
----

done.

=== react-hooks-typescript

.install packages
[source, bash]
----
npm i -ED parcel-bundler parcel-plugin-static-files-copy scss
npm i -ED typescript @types/node @types/react @types/react-dom
npm i -ED babel-core babel-preset-env babel-preset-react @babel/preset-typescript
npm i -E react react-dom
----

.key `package.json` features:
[source, json]
----
{
  "name": "react-hooks-ts-app",
  "main": "./src/index.html",
  "devDependencies": {
    "@babel/preset-typescript": "7.9.0",
    "@types/node": "13.9.2",
    "@types/react": "16.9.25",
    "@types/react-dom": "16.9.5",
    "babel-core": "6.26.3",
    "babel-preset-env": "1.7.0",
    "babel-preset-react": "6.24.1",
    "parcel-bundler": "1.12.4",
    "parcel-plugin-static-files-copy": "2.3.1",
    "pm2": "4.2.3",
    "sass": "1.26.3",
    "typescript": "3.8.3"
  },
  "dependencies": {
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "staticFiles": {
    "staticPath": "./src/public",
    "watcherGlob": "**"
  },
  "babel": {
    "presets": [
      "env",
      "react"
    ]
  },
  "scripts": {
    "dev": "parcel src/index.html --no-cache",
    "build": "parcel build src/index.html --no-cache",
    "start": "pm2 start 'npm run dev' --name app",
    "restart": "pm2 restart app",
    "stop": "pm2 kill",
    "logs": "pm2 logs"
  }
}
----

.edit file `main.tsx`:
[source, ts]
----
include::../react-hooks-ts/src/main.tsx[]
----

.edit file `components/App.tsx`:
[source, ts]
----
include::../react-hooks-ts/src/components/App.tsx[]
----

.edit file `components/UseStateApp.tsx`:
[source, ts]
----
include::../react-hooks-ts/src/components/UseStateApp.tsx[]
----

.edit file `components/UseReducerApp.tsx`:
[source, ts]
----
include::../react-hooks-ts/src/components/UseReducerApp.tsx[]
----

.edit file `components/UseContextStoreApp.tsx`:
[source, ts]
----
include::../react-hooks-ts/src/components/UseContextStoreApp.tsx[]
----

done.

=== preact-hooks-typescript

.install packages
[source, bash]
----
npm i -ED parcel-bundler parcel-plugin-static-files-copy scss
npm i -ED typescript @types/node
npm i -ED babel-core babel-preset-env babel-preset-preact @babel/preset-typescript
npm i -E preact
----

.key `package.json` features:
[source, json]
----
{
  "name": "react-hooks-ts-app",
  "main": "./src/index.html",
  "devDependencies": {
    "@babel/preset-typescript": "7.9.0",
    "@types/node": "13.9.2",
    "@types/react": "16.9.25",
    "@types/react-dom": "16.9.5",
    "babel-core": "6.26.3",
    "babel-preset-env": "1.7.0",
    "babel-preset-react": "6.24.1",
    "parcel-bundler": "1.12.4",
    "parcel-plugin-static-files-copy": "2.3.1",
    "pm2": "4.2.3",
    "sass": "1.26.3",
    "typescript": "3.8.3"
  },
  "dependencies": {
    "react": "16.13.1",
    "react-dom": "16.13.1"
  },
  "staticFiles": {
    "staticPath": "./src/public",
    "watcherGlob": "**"
  },
  "babel": {
    "presets": [
      "env",
      "react"
    ]
  },
  "scripts": {
    "dev": "parcel src/index.html --no-cache",
    "build": "parcel build src/index.html --no-cache",
    "start": "pm2 start 'npm run dev' --name app",
    "restart": "pm2 restart app",
    "stop": "pm2 kill",
    "logs": "pm2 logs"
  }
}
----

.edit file `components/AppUseState.tsx`:
[source, ts]
----
include::../preact-hooks-ts/src/components/AppUseState.tsx[]
----

.edit file `main.tsx`:
[source, ts]
----
include::../preact-hooks-ts/src/main.tsx[]
----

done.

== Links

- link:https://parceljs.org/[parcel]
- link:https://github.com/parcel-bundler/examples[parcel examples]
- link:https://reactjs.org/[react]
- link:https://preactjs.com/[preact]
- link:https://vuejs.org/[vue]

---
- link:https://github.com/parcel-bundler/awesome-parcel[GitHub: parcel-bundler/awesome-parcel]

---
ifdef::backend-html5[- link:./index.pdf[Documentation in PFD format]]
- link:{github-url}[GitHub repo]
- link:https://daggerok.github.io/{root-project-name}[GitHub pages]
