= {root-project-name} ({project-version})
////
image:https://travis-ci.org/daggerok/root-project-name.svg?branch=master["Build Status", link=github-url]
image:https://gitlab.com/daggerok/root-project-name/badges/master/build.svg["Build Status", link=gitlab-url]
image:https://img.shields.io/bitbucket/pipelines/daggerok/root-project-name.svg["Build Status", link=bitbucket-url]
////
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]

////
GitLab CI status:
image:https://gitlab.com/daggerok/{root-project-name}/badges/master/build.svg["Build Status", link={gitlab-url}]

BitBucket CI status:
image:https://img.shields.io/bitbucket/pipelines/daggerok/{root-project-name}.svg["Build Status", link={bitbucket-url}]
////

== Introduction

include::../README.adoc[tags=content]

== Implementation

=== basic example

.prepare project
[source,bash]
----
mkdir -p basic

echo "node_modules" >> basic/.gitignore
echo "dist" >> basic/.gitignore
echo '{"scripts":{"start":"parcel serve src/","build":"parcel build src/index.html"}}' > basic/package.json

cd basic/
npm init -y
npm i -D parcel-bundler
----

.prepare project files
[source,bash]
----
mkdir -p src
touch src/index.html
touch src/styles.css
touch src/main.js
----

.main.js
[source,javascript]
----
include::../basic/src/main.js[]
----

.styles.css
[source,javascript]
----
include::../basic/src/styles.css[]
----

.index.html
[source,html]
----
include::../basic/src/index.html[]
----

.start development
[source,bash]
----
npm start
----

open http://localhost:1234/

.build bundle
[source,bash]
----
npm run build
----

.verify result
[source,bash]
----
npm i -g serve
serve dist/
----

open http://localhost:5000/

=== babel-stage-0

parcel needed only .babelrc file and installed required presets

.add `.babelrc` file, install and configure presets: `env` and `stage-0`
[source,bash]
----
cp -Rf basic babel-stage-0
cd babel-stage-0/
echo '{"presets":["env","stage-0"]}' > .babelrc
npm i -D babel-preset-env babel-preset-stage-0
----

done.

=== react

.for React you need even less: just install react library and parcel will recognize everything for you!
[source,bash]
----
cp -Rf babel-stage-0 react
cd react/
npm i -S react react-dom
----

.add react component:
[source,javascript]
----
include::../react/src/components/echo-ehlo.js[]
----

.and update code in `src/main.js` file:
[source,javascript]
----
include::../react/src/main.js[]
----

build, run, verify...

done.

== Links

ifdef::backend-html5[- link:./index.pdf[Documentation in PFD format]]
- link:{github-url}[GitHub repo]
- link:https://daggerok.github.io/{root-project-name}[GitHub pages]
////
- link:{gitlab-url}[GitLab repo]
- link:https://daggerok.gitlab.io/{root-project-name}[GitLab pages]
- link:{bitbucket-url}[BitBucket repo]
////
