= {root-project-name} ({project-version})
Maksim Kostromin <daggerok@gmail.com>
{docdatetime}
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: prettify
:numbered:
:icons: font
:hide-uri-scheme:
:revnumber: {project-version}
:example-caption!:

Travis CI status:
image:https://travis-ci.org/daggerok/{root-project-name}.svg?branch=master["Build Status", link={github-url}]

== Introduction

include::../README.adoc[tags=content]

== Implementation

=== basic example

.prepare project
[source,bash]
----
mkdir -p basic

echo "node_modules" >> basic/.gitignore
echo "dist" >> basic/.gitignore
echo ".cache" >> basic/.gitignore
echo '{"scripts":{"start":"parcel src/","build":"parcel build src/index.html"}}' > basic/package.json

cd basic/
npm init -y
npm i -D parcel-bundler
----

.prepare project files
[source,bash]
----
mkdir -p src
touch src/index.html
touch src/styles.css
touch src/main.js
----

.main.js
[source,javascript]
----
include::../basic/src/main.js[]
----

.styles.css
[source,javascript]
----
include::../basic/src/styles.css[]
----

.index.html
[source,html]
----
include::../basic/src/index.html[]
----

.start development
[source,bash]
----
npm start
----

open http://localhost:1234/

.build bundle
[source,bash]
----
npm run build
----

.verify result
[source,bash]
----
npm i -g serve
serve dist/
----

open http://localhost:5000/

=== babel stage-0

parcel needed only .babelrc file and installed required presets

.add `.babelrc` file, install and configure presets: `env` and `stage-0`
[source,bash]
----
cp -Rf basic babel-stage-0
cd babel-stage-0/
echo '{"presets":["env","stage-0"]}' > .babelrc
npm i -D babel-preset-env babel-preset-stage-0
----

.now you can use some cool JS features:
[source,javascript]
----
include::../babel-stage-0/src/main.js[tags=content]
----

done.

=== react

.for React you need even less: just install react library and parcel will recognize everything for you!
[source,bash]
----
cp -Rf babel-stage-0 react
cd react/
npm i -S react react-dom
npm i -D babel-preset-react
echo '{"presets":["env","react"]}' > .babelrc
----

.add react component:
[source,javascript]
----
include::../react/src/components/echo-ehlo.js[]
----

.and update code in `src/main.js` file:
[source,javascript]
----
include::../react/src/main.js[tags=content]
----

build, run, verify...

done.

=== preact

.do necessary updates from react example:
[source,bash]
----
cp -Rf react preact
cd preact/

npm rm react react-dom babel-preset-react

npm i -S preact preact-compat
npm i -D babel-preset-preact babel-plugin-transform-class-properties

echo '{"presets":["env","preact"],"plugins":["transform-class-properties"]}' > .babelrc
----

.implement preact component:
[source,javascript]
----
include::../preact/src/components/echo-ehlo.js[]
----

.update entry point:
[source,javascript]
----
include::../preact/src/main.js[tags=content]
----

done.

=== vue

.to be able build vue apps, in addition to babel example you only need install vue and two dev packages:
[source,bash]
----
cp -Rf babel-stage-0 vue
cd vue/
npm i -S vue
npm i -D babel-preset-vue @vue/component-compiler-utils vue-template-compiler
echo '{"presets":["env","vue"]}' > .babelrc
----

.add vue component file: `App.vue`
[source,html]
----
include::../vue/src/components/App.vue[]
----

.main.js
[source,javascript]
----
include::../vue/src/main.js[tags=content]
----

=== yaml

.to be able to parse YAML we need js-yaml package:
[source,bash]
----
cp -Rf basic yaml
cd yaml/
npm i -ES js-yaml
----

.add YAML file:
[source,yaml]
----
include::../yaml/src/app.yaml[]
----

.main.js
[source,javascript]
----
include::../yaml/src/main.js[tags=content]
----

=== markdown

.to be able to parse YAML we need parcel-plugin-markdown package:
[source,bash]
----
cp -Rf basic markdown
cd markdown/
npm i -ED parcel-plugin-markdown
----

.add `app.md` file:
[source,markdown]
----
include::../markdown/src/app.md[]
----

.main.js
[source,javascript]
----
include::../markdown/src/main.js[tags=content]
----

NOTE: See also `markdowns` and `markdowns2` projects for non single md-file parsing use case...

=== markdowns (2)

example how we can handle lazy loading with parcel for markdown files lazy processing on runtime

.add `./src/posts` folder with some posts in markdown format:
[source,bash]
----
tree markdowns2/src/posts/
markdowns2/src/posts/
└── 2018
    └── 06
        ├── 29
        │   ├── 01-ololo.md
        │   └── 02-trololo.md
        └── 30
            ├── 01-javascript.md
            └── 02-bash.md
----

.`main.js` implementation:
[source,javascript]
----
include::../markdowns2/src/main.js[tags=content]
----

== Links

- link:https://parceljs.org/[parcel]
- link:https://github.com/parcel-bundler/examples[parcel examples]
- link:https://reactjs.org/[react]
- link:https://preactjs.com/[preact]
- link:https://vuejs.org/[vue]

---
- link:https://github.com/parcel-bundler/awesome-parcel[GitHub: parcel-bundler/awesome-parcel]

---
ifdef::backend-html5[- link:./index.pdf[Documentation in PFD format]]
- link:{github-url}[GitHub repo]
- link:https://daggerok.github.io/{root-project-name}[GitHub pages]
