name: Parcel 2.x
on: [push]
env:
  NODE_VERSION: 18.4.0
jobs:
  v2-posthtml-include:
    name: posthtml-include
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y curl httpie
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.docker
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json', '**/pom.xml') }}
      - run: npm --prefix v2/posthtml-include i -E
      - run: npm --prefix v2/posthtml-include run build
      - run: npm --prefix v2/posthtml-include start
      - run: npm --prefix v2/posthtml-include run logs &
      - run: npm_config_yes=true npx wait-port 1234
      - run: curl 127.0.0.1:1234
      - run: npm --prefix v2/posthtml-include stop
  v2-solid:
    name: solid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install -y curl httpie
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.npm
            ~/.docker
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json', '**/pom.xml') }}
      - run: npm --prefix v2/solid i -E
      - run: npm --prefix v2/solid run build
      - run: npm --prefix v2/solid start
      - run: npm --prefix v2/solid run logs &
      - run: npm_config_yes=true npx wait-port 1234
      - run: curl 127.0.0.1:1234
      - run: npm --prefix v2/solid stop
